import dotenv from 'dotenv';

dotenv.config();

const environments = {
  ALCHEMY_API_ENDPOINT: process.env.ALCHEMY_API_ENDPOINT,
  NETWORK_ID: process.env.NETWORK_ID,

  PANCAKE_PREDICTION_CONTRACT_ADDRESS:
    process.env.PANCAKE_PREDICTION_CONTRACT_ADDRESS,
  PANCAKE_PREDICTION_TREASURY_FEE: process.env.PANCAKE_PREDICTION_TREASURY_FEE,
  PANCAKE_PREDICTION_BET_AMOUNT: process.env.PANCAKE_PREDICTION_BET_AMOUNT,

  FULFILL_PHASE_END_TIME_IN_SECOND:
    process.env.FULFILL_PHASE_END_TIME_IN_SECOND,
  CLAIM_PHASE_END_TIME_IN_SECOND: process.env.CLAIM_PHASE_END_TIME_IN_SECOND,
  ANALYZE_PHASE_START_TIME_FROM_SECOND:
    process.env.ANALYZE_PHASE_START_TIME_FROM_SECOND,
  MIN_ROI: process.env.MIN_ROI,
  NUMBER_OF_ROUNDS_TO_CLAIM: process.env.NUMBER_OF_ROUNDS_TO_CLAIM,

  MASTER_WALLET_PRIVATE_KEY: process.env.MASTER_WALLET_PRIVATE_KEY,

  REDIS_USERNAME: process.env.REDIS_USERNAME,
  REDIS_PASSWORD: process.env.REDIS_PASSWORD,
  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
};

export default environments;
